[theme]
base = "dark"
primaryColor = "#FB9A32"
backgroundColor = "#0D0F19"
secondaryBackgroundColor = "#171A26"
textColor = "#F4F2EC"
font = "sans serif"

[server]
headless = true
port = 8501
address = "0.0.0.0"
enableXsrfProtection = false

[browser]
gatherUsageStats = false